#config file for Hexacopter with sideways delta_arm
rate:                         100             #ros rate in [Hz]

#manipulator geometry parameters:
manipulator:
  geometry/nozzle:             0.15            #length of appendage from delta platform in [m]
  geometry/drone2base_x:       0.3             #offset of base of delta from CoM of drone in [m]
  geometry/drone2base_z:       0.05            #offset of base of delta from CoM of drone in [m]
  geometry/base_pitch:         90              #rotation of delta_arm base in pitch direction (0 is down, 90 is forward) in [degrees]



