#config file for Hexacopter with sideways delta_arm
rate:                         100             #ros rate in [Hz]

#manipulator geometry parameters:
manipulator:
  geometry/sp:                0.06            #size of platform (see kinematics paper) in [m]
  geometry/sb:                0.34            #size of base (see kinematics paper) in [m]
  geometry/l:                 0.47            #distal joint length in [m]
  geometry/L:                 0.2             #proximal joint length in [m]

#dynamixel servo parameters
  servo/dir1:                 false           #reverse servo 1 rotation direction?
  servo/dir2:                 true            #reverse servo 2 rotation direction?
  servo/dir3:                 false           #reverse servo 3 rotation direction?

#uav geometry parameters (in fcu coordinate frame):
  tooltip/tip_init_x:         0.6             #initial x offset of delta tip from base in [m]
  tooltip/tip_init_y:         0.0             #initial y offset of delta tip from base in [m]
  tooltip/tip_init_z:         0.0             #initial z offset of delta tip from base in [m]



