#config file for Hexacopter with sideways delta_arm
rate:                         100             #ros rate in [Hz]

#manipulator geometry parameters:
manipulator:
  geometry/nozzle:             0.15            #length of appendage from delta platform in [m]
  geometry/drone2base_x:       0.3             #offset of base of delta from CoM of drone in [m]
  geometry/drone2base_z:       0.05            #offset of base of delta from CoM of drone in [m]
  geometry/base_pitch:         90              #rotation of delta_arm base in pitch direction (0 is down, 90 is forward) in [degrees]

#mavros
mavros:
  local_position/tf/send:     true            #send tf data from drone
  fcu_url:                    "udp://:14540@localhost:14557"
  #gcs_url:                    "udp://:14540@localhost:14557"

#dynamixels
# dynamixel:
#   port:

#todo: set servo params from this launch file
#rewrite dynamixel code with config options



