#Params for vrpn_client
  vicon:
    model_list:                                         [hexacopter, hex_tooltip]
    # model_list:                                         [hexacopter]
    server_address:                                     "192.168.0.100"
    publish_tf:                                         true

  # mavros:
  #   local_position/tf/send:                             true