#Params for vrpn_client
  object_name:                                          "hexacopter"
  vrpn_server_ip:                                       "192.168.0.100"
  vrpn_coordinate_system:                               "vicon"
  timestamping_system:                                  "ros"
  verbose:                                              true

  translational_estimator:
    kp:                                                 0.5
    kv:                                                 0.5 
  rotational_estimator:
    orientation_estimate_initial_covariance:            100.0
    rate_estimate_initial_covariance:                   100.0
    orientation_process_covariance:                     0.000002
    rate_process_covariance:                            10.0
    orientation_measurementCovariance:                  0.001
    outlier_rejection_method:                           "mahalanobis_distance"
    outlier_rejection_mahalanobis_threshold:            4.0
    outlier_rejection_subsequent_threshold_degrees:     30.0
    outlier_rejection_subsequent_maximum_count:         50.0
    output_minimal_quaternions:                         false
    output_minimal_quaternions:                         false

  mavros:
    conn/timesync_rate:                                 0.0